fun main(args: Array<String>) {
    exceptionExample()
}
fun exceptionExample(){
    throw Exception()
}
